import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"
import { test } from "node:test"

import { build } from "../scripts/build-burials.js"

const ROOT = path.resolve(import.meta.dirname, "..")
const EVIDENCE = path.join(ROOT, "source", "burials-evidence", "burials-evidence.json")
const ROWS = path.join(ROOT, "source", "handoff", "burials", "rows.json")
const WEB = path.join(ROOT, "web")

// The exhibit and the RERUM load path are meant to speak one vocabulary. If a key is added to
// one and not the other, a reader silently stops seeing a claim they used to get.
const CLAIM_KEYS = [
  "description",
  "birthDate",
  "deathDate",
  "ageAtDeath",
  "relationship",
  "relatedTo",
  "engravingText",
  "familyGroup"
]

function data() {
  return build(JSON.parse(fs.readFileSync(EVIDENCE, "utf8")), JSON.parse(fs.readFileSync(ROWS, "utf8")))
}

test("every cited page has a photograph that actually ships", () => {
  const d = data()
  assert.ok(Object.keys(d.pages).length > 0, "the index cites no pages at all")

  for (const record of d.records) {
    const page = d.pages[record.page]
    assert.ok(page, `${record.id} cites page ${record.page}, which the index does not carry`)
    assert.ok(page.image, `${record.page} carries no image path`)
    assert.ok(
      !path.isAbsolute(page.image) && !page.image.startsWith(".."),
      `${page.image} must stay relative so the exhibit works under any base path`
    )
    assert.ok(
      fs.existsSync(path.join(WEB, page.image.replace(/\//g, path.sep))),
      `the exhibit would show a broken image: ${page.image} is not in web/`
    )
  }
})

test("every measured line falls inside the page it is drawn on", () => {
  const d = data()
  for (const record of d.records) {
    if (!record.rect) continue
    const page = d.pages[record.page]
    const { x0, y0, x1, y1 } = record.rect
    assert.ok(x1 > x0 && y1 > y0, `${record.id} has a rectangle with no area`)
    assert.ok(x0 >= 0 && y0 >= 0, `${record.id} starts off the page`)
    assert.ok(x1 <= page.width && y1 <= page.height, `${record.id} runs past the edge of ${record.page}`)
  }
})

test("the index publishes only the loader's claim vocabulary", () => {
  const d = data()
  for (const record of d.records) {
    for (const key of Object.keys(record.claims)) {
      assert.ok(CLAIM_KEYS.includes(key), `${record.id} publishes an unknown claim: ${key}`)
    }
    for (const claim of record.claimList) {
      if (claim.key === "familyGroup") {
        // The one structured claim: the exhibit draws it as a bracket, not as text.
        assert.equal(typeof claim.value.value, "string", `${record.id}:familyGroup has no name`)
        continue
      }
      assert.equal(typeof claim.value, "string", `${record.id}:${claim.key} must render as text`)
      assert.ok(claim.value.trim(), `${record.id}:${claim.key} is empty`)
    }
  }
})

test("each line is quoted from the typescript rather than rewritten", () => {
  const d = data()
  const evidence = JSON.parse(fs.readFileSync(EVIDENCE, "utf8"))
  const byId = new Map(evidence.records.map((r) => [r.id, r]))

  for (const record of d.records) {
    const source = byId.get(record.id)
    assert.ok(source, `${record.id} is not in the transcription`)
    assert.equal(record.claims.description, source.entryText)
  }
})

test("a second witness points at a real inscription photograph", () => {
  const d = data()
  const witnessed = d.records.filter((r) => r.engraving)
  assert.ok(witnessed.length > 0, "no burial is corroborated by an inscription")

  for (const record of witnessed) {
    const page = d.pages[record.engraving.page]
    assert.ok(page, `${record.id} cites inscription page ${record.engraving.page}, which is not published`)
    assert.ok(record.engraving.text.trim(), `${record.id} offers an empty inscription`)
    assert.ok(
      fs.existsSync(path.join(WEB, page.image.replace(/\//g, path.sep))),
      `the inscription photograph is missing: ${page.image}`
    )
  }
})

test("a family bracket always leads somewhere real", () => {
  const d = data()
  const ids = new Set(d.records.map((r) => r.id))
  const grouped = d.records.filter((r) => r.claims.familyGroup)
  assert.ok(grouped.length > 0, "no burial is filed under a family group")

  for (const record of grouped) {
    const group = record.claims.familyGroup
    assert.ok(
      ids.has(group.headOf),
      `${record.id} points at head of group ${group.headOf}, which the index does not contain`
    )
    assert.notEqual(group.headOf, record.id, `${record.id} is filed under itself`)
    assert.ok(group.value.trim(), `${record.id} names no head of group`)
  }
})

test("the published index is current with its sources", () => {
  const out = path.join(WEB, "data", "burials.json")
  if (!fs.existsSync(out)) return // generated by `npm run build`; not every checkout has it
  const published = JSON.parse(fs.readFileSync(out, "utf8"))
  const fresh = data()
  assert.equal(
    JSON.stringify(published.records),
    JSON.stringify(fresh.records),
    "web/data/burials.json is stale; run `npm run build`"
  )
})
