/**
 * The RERUM agent this instance writes as.
 *
 * RERUM stamps `__rerum.generatedBy` on every record from the agent behind the bearer
 * token, so "which app made this data" is decided by the token in `.env` and nowhere
 * else. This module reads that identity back out of the JWT so the app can assert it
 * instead of guessing, and so a stale sandbox token cannot quietly keep attributing
 * McElwee edits to `sandbox@rerum.io`.
 */

/** Claim RERUM uses to carry the agent IRI of the authenticated application. */
export const AGENT_CLAIM = "http://store.rerum.io/agent"

/**
 * The shared TinyThings sandbox agent every 2018 McElwee record was written under.
 * Anything generated by this app should NOT be attributed to it.
 */
export const SHARED_SANDBOX_AGENT = "http://devstore.rerum.io/v1/id/5afeebf3e4b0b0d588705d90"

/**
 * Decode a JWT payload without verifying its signature.
 *
 * Signature verification is RERUM's job when the token is presented upstream; here we
 * only read our own locally configured token to report which agent we are.
 */
export function decodeJwtPayload(token) {
  const encoded = String(token ?? "").split(".")[1]
  if (!encoded) return null
  try {
    const json = Buffer.from(encoded, "base64url").toString("utf8")
    return JSON.parse(json)
  } catch {
    return null
  }
}

export function agentIriFromToken(token) {
  const payload = decodeJwtPayload(token)
  if (!payload) return null
  const claim = payload[AGENT_CLAIM] ?? payload.azp ?? payload.client_id
  return typeof claim === "string" && claim.trim() ? claim.trim() : null
}

export function tokenExpiryMs(token) {
  const payload = decodeJwtPayload(token)
  const exp = payload?.exp
  return Number.isFinite(exp) ? exp * 1000 : null
}

export function isTokenExpired(token, now = Date.now()) {
  const expires = tokenExpiryMs(token)
  // An unreadable token has no expiry to enforce; the upstream call reports the problem.
  if (expires === null) return false
  return now >= expires
}

/**
 * Describe the write identity of a config, and whether it is safe to write with.
 *
 * @returns {{agentIri: string|null, registered: boolean, isSharedSandbox: boolean, matchesExpected: boolean, problem: string|null}}
 */
export function inspectAgent({ accessToken, refreshToken, expectedAgentIri }) {
  const agentIri = agentIriFromToken(accessToken)
  const registered = Boolean(agentIri || refreshToken)

  if (!registered) {
    return {
      agentIri: null,
      registered: false,
      isSharedSandbox: false,
      matchesExpected: false,
      problem:
        "No RERUM credentials in .env. Reads work, but writes are unattributed and will be rejected by RERUM. Copy sample.env to .env and register."
    }
  }

  const isSharedSandbox = agentIri === SHARED_SANDBOX_AGENT
  const matchesExpected = expectedAgentIri ? agentIri === expectedAgentIri : true

  if (isSharedSandbox) {
    return {
      agentIri,
      registered: true,
      isSharedSandbox,
      matchesExpected,
      problem:
        "Credentials belong to the shared TinyThings sandbox agent. Records would be attributed to sandbox@rerum.io rather than to this app. Register an McElwee agent and put its tokens in .env."
    }
  }

  if (!matchesExpected) {
    return {
      agentIri,
      registered: true,
      isSharedSandbox,
      matchesExpected,
      problem: `Token agent ${agentIri} does not match EXPECTED_AGENT_IRI ${expectedAgentIri}.`
    }
  }

  return { agentIri, registered: true, isSharedSandbox, matchesExpected, problem: null }
}
