import "dotenv/config"

import { readConfig } from "../server/config.js"
import { inspectAgent, tokenExpiryMs } from "../server/agent.js"

/**
 * Report which RERUM agent this checkout would write as.
 *
 * The whole point of retiring the Java app is that new data should be generated by an
 * agent registered for McElwee rather than the shared TinyThings sandbox, and the only
 * way to know which one you have is to look inside the token.
 */
const config = readConfig()
const status = inspectAgent(config)

console.log("McElwee RERUM identity")
console.log("  upstream        " + config.apiAddr)
console.log("  agent IRI       " + (status.agentIri ?? "(none)"))
console.log("  token expires   " + (tokenExpiryMs(config.accessToken) ? new Date(tokenExpiryMs(config.accessToken)).toISOString() : "(unreadable or absent)"))
console.log("  EXPECTED_AGENT  " + (config.expectedAgentIri || "(not set)"))

if (status.problem) {
  console.error("\n  PROBLEM  " + status.problem)
  process.exitCode = 1
} else {
  console.log("\n  OK  Writes from `npm start` will be attributed to this agent.")
}
